name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.8
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python environment
        run: |
          python3.8 -m venv venv
          venv/bin/python -m pip install -r requirements-dev.txt
          venv/bin/python -m pip install -e .[dev]
      - run: venv/bin/pytest --cov-report=term --cov-report=xml --junit-xml=report.xml
      - run: venv/bin/flake8 src tests
      - run: venv/bin/mypy --no-error-summary src tests
      - run: venv/bin/pylint --jobs 0 --score n src tests
      - run: venv/bin/yapf -dpr src tests
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
      - name: Upload JUnit report
        uses: actions/upload-artifact@v3
        with:
          name: junit-report
          path: report.xml

  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.8
    steps:
      - uses: actions/checkout@v4
      - name: Build the project
        run: |
          python3.8 -m venv venv
          venv/bin/python -m pip install build
          venv/bin/python -m build .
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist

  build_docs:
    runs-on: ubuntu-latest
    container:
      image: python:3.8
    steps:
      - uses: actions/checkout@v4
      - name: Build the docs
        run: |
          python3.8 -m venv venv
          venv/bin/python -m pip install -r requirements-dev.txt
          venv/bin/python -m pip install -e .[dev]
          venv/bin/sphinx-build docs public
      - name: Upload pages content
        uses: actions/upload-artifact@v3
        with:
          name: pages-content
          path: public